[workspace]
members = [
  "crates/derive-stack-queue",
  "crates/echo-batched",
  "crates/stack-queue"
]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1
