[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "stack-queue"
version = "0.0.1-beta.9"
description = "Heapless auto-batching queue"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/stack-queue/"

[dependencies]
async_t = "0.7"
cache-padded = "1.2"
derive-stack-queue = { version  = "0.0.1-beta.9", path = "../derive-stack-queue"}
diesel = { version = "2", optional = true }
pin-project = "1"
static_assertions = "1.1.0"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
futures = "0.3.25"
tokio = { version = "1", features = ["rt", "sync", "macros", "rt-multi-thread"] }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5.6", features = [ "futures" ] }

[lib]
doctest = false
bench = false

[features]
default = []
boxed = ["async_t/boxed"]
diesel-associations = ["diesel"]

[package.metadata.docs.rs]
features = ["boxed", "diesel-associations"]