[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "stack-queue"
version = "0.0.1-beta.2"
description = "Heapless auto-batching queue"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/stack-queue/"

[dependencies]
async_t = "0.7"
bit-bounds = "0.1.0"
cache-padded = "1.2"
const-assert = "1.0.0"
pin-project = "1"
rayon = "1.5"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
futures = "0.3.24"
tokio = { version = "1", features = ["rt", "macros", "time"] }

[lib]
doctest = false
bench = false