[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "stack-queue"
version = "0.1.0"
description = "Heapless auto-batching queue"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/stack-queue/"

[dependencies]
async_t = "0.7"
async-local = "0.8"
async-std = { version = "1", features = ["attributes"], optional = true }
cache-padded = "1.2"
derive-stack-queue = { version = "0.1.0", path = "../derive-stack-queue" }
diesel = { version = "2", optional = true }
pin-project = "1"
static_assertions = "1.1"
tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "rt",
  "sync",
], optional = true }

[dev-dependencies]
futures = "0.3.25"

[target.'cfg(loom)'.dependencies]
futures-test = "0.3.25"
loom = { version = "0.5.6", features = ["futures"] }

[lib]
doctest = false
bench = false

[features]
default = ["tokio-runtime"]
boxed = ["async_t/boxed", "async-local/boxed"]
# Implement [BelongsTo](https://docs.rs/diesel/2/diesel/associations/trait.BelongsTo.html) for [TaskRef<T>](https://docs.rs/stack-queue/latest/stack_queue/task/struct.TaskRef.html)
diesel-associations = ["diesel"]
tokio-runtime = [
  "tokio",
  "async-local/tokio-runtime",
  "derive-stack-queue/tokio-runtime",
]
async-std-runtime = [
  "async-std",
  "async-local/async-std-runtime",
  "derive-stack-queue/async-std-runtime",
]

[package.metadata.docs.rs]
features = ["tokio-runtime", "diesel-associations"]
all-features = false
rustdoc-args = ["--cfg", "docsrs"]
