[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "stack-queue"
version = "0.0.1-beta.5"
description = "Heapless auto-batching queue"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/stack-queue/"

[dependencies]
async_t = "0.7"
bit-bounds = "0.1.0"
cache-padded = "1.2"
const-assert = "1.0.0"
derive-stack-queue = { version  = "0.0.1-beta.5", path = "../derive-stack-queue"}
diesel = { version = "2", optional = true }
pin-project = "1"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
futures = "0.3.25"
tokio = { version = "1", features = ["rt", "macros", "time", "rt-multi-thread"] }

[lib]
doctest = false
bench = false

[features]
default = []
diesel-associations = ["diesel"]

[package.metadata.docs.rs]
features = ["diesel-associations"]